services:
  - type: web
    name: alex-image-bot
    runtime: image
    repo: https://github.com/ppvekt-afk/alex-image-bot
    plan: free
    dockerCommand: python bot.py
    buildCommand: pip install -r requirements.txt
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
